Repository grouparoo/www.grouparoo.com, pull requests merged in 2020-10, with the labels that each got.

#8 Auth for DockerHub in CI
  .circleci/config.yml
Labels: dependencies

#15 lock dependency versions
  package-lock.json
  package.json
Labels: dependencies

#16 Upgrading grouparoo page
  pages/docs/deployment/upgrading-grouparoo.mdx
  public/images/docs/deployment/in-app-versions.png
  public/images/docs/deployment/release-notes.png
  public/images/docs/deployment/upgrade-diff.png
  utils/blogPosts.ts
  utils/docEngine.tsx
  utils/docPosts.ts
Labels: documentation, enhancement

#17 Common Issues Page
  components/docs/havingProblems.tsx
  pages/docs/deployment.mdx
  pages/docs/deployment/aws-and-k8s.mdx
  pages/docs/deployment/common-issues.mdx
  pages/docs/deployment/docker.mdx
  pages/docs/deployment/heroku.mdx
  pages/docs/deployment/monitoring-and-debugging.mdx
  pages/docs/deployment/upgrading-grouparoo.mdx
  utils/blogPosts.ts
  utils/docPosts.ts
Labels: enhancement

#21 Jobs posting sections should always be expanded
  components/jobBoard.tsx
Labels: hacktoberfest-accepted

#19 Add guest post on TS
  components/blog/authorBox.tsx
  data/authors.ts
  pages/blog/any-wreaks-havoc-on-overloads.mdx
  pages/blog/index.tsx
  public/images/authors/tiger_oakes.png
  utils/blogPosts.ts
  utils/docPosts.ts
Labels: hacktoberfest-accepted

#23 move classname to className so tweet renders
  pages/blog/any-wreaks-havoc-on-overloads.mdx
Labels: bug

#25 Using Typescript to create a Robust API between your frontend and backend
  pages/blog/typescript-frontend-backend.mdx
  public/posts/typescript-frontend-backend/keyboard.jpg
  public/posts/typescript-frontend-backend/screenshot-1.png
  public/posts/typescript-frontend-backend/screenshot-2.png
  utils/blogPosts.ts
  utils/docPosts.ts
Labels: enhancement

#24 Pricing page
  components/footer.tsx
  components/navigation.tsx
  pages/pricing.tsx
  scss/grouparoo.scss
  utils/getSitemap.ts
Labels: hacktoberfest-accepted

#34 Update dependencies, remove react-markdown
  package-lock.json
  package.json
Labels: dependencies

#36 Disable _next listing when deployed
  vercel.json
Labels: enhancement
