Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-05, with the labels that each got.

#425 [whats new] pardot
  pages/whats-new/2021-05-04-pardot.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/posts/releases/2021-05-04-pardot.png
  public/sitemap.xml
Labels: enhancement

#417 Updated Nav Bar and Fixed Banners
  __tests__/integration/comparisons.ts
  components/icons.ts
  components/navigation.tsx
  pages/solutions/[id].tsx
  scss/grouparoo.scss
Labels: enhancement

#427 Setup ad conversion scripts
  components/adConversionsScript.tsx
  components/layouts/main.tsx
  components/subscribe.tsx
  pages/meet.tsx
Labels: enhancement

#431 Update to prettier v2.3.0
  components/layouts/main.tsx
  package-lock.json
  package.json
Labels: dependencies

#430 Adjusted Pricing Page UI
  pages/pricing.tsx
  scss/grouparoo.scss
Labels: bug

#433 Adjusted top level nav
  components/icons.ts
  components/navigation.tsx
  scss/grouparoo.scss
Labels: enhancement

#440 Blog post - Build a Navbar Mega Menu Using React Bootstrap
  pages/blog/build-a-mega-menu-with-react-bootstrap.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/build-a-mega-menu-with-react-bootstrap/before-tutorial.png
  public/posts/build-a-mega-menu-with-react-bootstrap/final-on-www.png
  public/posts/build-a-mega-menu-with-react-bootstrap/finished-mobile-tutorial.png
  public/posts/build-a-mega-menu-with-react-bootstrap/finished-tutorial.png
  public/posts/build-a-mega-menu-with-react-bootstrap/in-process-tutorial.png
  public/posts/build-a-mega-menu-with-react-bootstrap/mega-menu.png
  public/posts/build-a-mega-menu-with-react-bootstrap/mockups-screenshot.png
  public/sitemap.xml
Labels: enhancement

#444 Posthog instrumentation
  components/layouts/main.tsx
  components/posthog.tsx
  components/subscribe.tsx
  package-lock.json
  package.json
  pages/meet.tsx
Labels: enhancement

#445 Replace `Nav.Link` with `div` in Header
  components/navigation.tsx
Labels: bug

#439 Added modern data stack page and adjusted template
  components/solutions/categoryPage.tsx
  pages/solutions/[id].tsx
  pages/solutions/customer-data-platform.mdx
  pages/solutions/modern-data-stack.mdx
  pages/solutions/reverse-etl.mdx
  public/sitemap.xml
  scss/grouparoo.scss
  utils/solutionsPages.ts
Labels: enhancement

#447 [blog] - varchar 191 post
  pages/blog/varchar-191.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/varchar-191/210515-varchar191.png
  public/sitemap.xml
Labels: enhancement

#452 Removed blog/added docs to nav
  components/navigation.tsx
Labels: enhancement

#451 updating etl graphic
  public/images/home/solutions/categories/etl.svg
Labels: enhancement

#453 Update modern data stack page
  components/footer.tsx
  components/navigation.tsx
  components/solutions/index.tsx
  components/solutions/sectionDivider.tsx
  pages/solutions/modern-data-stack.mdx
  public/images/home/solutions/categories/modern-data-stack.png
Labels: enhancement

#454 Google Analytics
  components/googleAnalytics.tsx
  components/layouts/main.tsx
  next.config.js
  pages/jobs/[id].tsx
Labels: enhancement

#456 Remove double-count for GA on Next router change
  components/googleAnalytics.tsx
Labels: bug

#455 Removing/updating references to bootstrapped property
  components/docs/plugins/tableSource.tsx
  pages/docs/cli/config.mdx
  pages/docs/config/sources/community.mdx
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/running/testing.mdx
  pages/docs/tutorials/app-example-config.mdx
Labels: documentation

#457 Remove Plausible Analytics
  components/layouts/main.tsx
  components/plausibleAnalytics.tsx
Labels: enhancement

#458 Add Sync Modes to Product Concepts
  pages/docs/getting-started/product-concepts.mdx
Labels: enhancement

#443 [what's new] Accessing Customer.io APP API.
  pages/whats-new/2021-05-13-customerio-app-api-key.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/sitemap.xml
Labels: documentation, enhancement

#460 `ImageInBrowserFrame` component
  components/imageInBrowserFrame.tsx
  pages/index.tsx
  pages/integrations/[type]/[plugin].tsx
  pages/integrations/bigquery-to-salesforce.tsx
  pages/integrations/postgres-to-hubspot.tsx
  pages/integrations/postgres-to-salesforce.tsx
  pages/solutions/education.tsx
  pages/solutions/healthcare.tsx
  pages/solutions/marketers.tsx
  scss/grouparoo.scss
Labels: enhancement

#462 new meet pg, added script to run app w telemetry
  package.json
  pages/meet.tsx
Labels: enhancement

#464 Integrations update
  __tests__/pages/integrations.tsx
  data/plugins/index.ts
  data/plugins/mongodb.ts
  data/plugins/pardot.ts
  data/plugins/sqlite.ts
  pages/integrations.tsx
  public/images/home/integrations/mongodb/mongodb.svg
  public/images/home/integrations/pardot/pardot.svg
  public/images/home/integrations/sqlite/sqlite.svg
Labels: enhancement

#469 Publishing workflow updates
  pages/docs/development/publishing.mdx
  public/images/docs/development/grouparoo-release-process.png
  public/images/docs/development/publish-action.png
Labels: enhancement

#471 switched order of titles on blog posts
  pages/blog/[post].tsx
Labels: enhancement

#461 Add script to generate plugin manifest
  components/docs/pluginsList.tsx
  public/plugins/v1/manifest.json
  scripts/generate_plugin_json.ts
  scripts/github_action
Labels: enhancement

#472 Add reference doc for Snowflake plugin.
  components/docs/plugins/columnarSource.tsx
  components/docs/plugins/querySource.tsx
  data/docs-nav.ts
  data/plugins/snowflake.ts
  pages/docs/plugins/grouparoo-snowflake.mdx
  public/sitemap.xml
Labels: documentation, enhancement

#476 Add MySQL reference doc.
  data/docs-nav.ts
  data/plugins/mysql.ts
  pages/docs/plugins/grouparoo-mysql.mdx
  public/sitemap.xml
Labels: documentation, enhancement

#479 Collapse the lighthouse report comment
  scripts/write_lighthouse_comment.ts
Labels: enhancement

#478 Add Redshift reference doc.
  data/docs-nav.ts
  data/plugins/redshift.ts
  pages/docs/plugins/grouparoo-redshift.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation, enhancement

#485 Upgrading to v0.4 + Slow migration guide
  data/docs-nav.ts
  pages/docs/support/common-issues.mdx
  pages/docs/support/upgrading-grouparoo.mdx
  pages/docs/support/upgrading-grouparoo/v01-v02.mdx
  pages/docs/support/upgrading-grouparoo/v02-v03.mdx
  pages/docs/support/upgrading-grouparoo/v03-v04.mdx
  public/sitemap.xml
Labels: enhancement
