Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-11, with the labels that each got.

#753 Fixes layout issues with new giant fonts
  components/bigArrow.tsx
  components/home/integrationCard.tsx
  data/plugins/index.ts
  pages/integrations/[type]/[plugin].tsx
  public/images/home/integrations/default/cloud.png
  public/images/home/integrations/default/database.png
  scss/grouparoo.scss
Labels: bug

#774 Sitemap updates
  components/footer.tsx
  pages/public-sitemap.tsx
Labels: enhancement

#775 Use Github feature request template
  next.config.js
Labels: enhancement

#777 update dataflow diagram
  pages/docs/development/dataflow.mdx
Labels: documentation

#779 Fix /solutions/marketers 404 error
  components/Navigation.tsx
  next.config.js
Labels: bug

#780 Orchestration Docs
  data/docs-nav.ts
  pages/docs/cli/run.mdx
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/running.mdx
  pages/docs/running/orchestration.mdx
  pages/docs/support/rest-api.mdx
  pages/solutions/census-alternative.mdx
  pages/solutions/hightouch-alternative.mdx
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#782 Fix fonts
  pages/_document.tsx
  scss/grouparoo.scss
Labels: bug

#783 types-of-apis blogpost
  pages/blog/types-of-apis.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/types-of-apis/hive.jpg
  public/sitemap.xml
Labels: enhancement

#781 Add ClickHouse plugin
  README.md
  data/docs-nav.ts
  data/plugins/clickhouse.ts
  data/plugins/googleBigQuery.ts
  data/plugins/index.ts
  pages/docs/config/code-config/apps.mdx
  pages/docs/plugins/grouparoo-clickhouse.mdx
  pages/whats-new/2021-11-15-clickhouse.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/images/home/integrations/clickhouse/add-clickhouse-app.png
  public/images/home/integrations/clickhouse/clickhouse-query-mode.png
  public/images/home/integrations/clickhouse/clickhouse-table-mode.png
  public/images/home/integrations/clickhouse/clickhouse.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#784 "What is Data Transformation" blogpost
  pages/blog/what-is-data-transformation.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/what-is-data-transformation/butterfly.jpg
  public/sitemap.xml
Labels: enhancement

#786 Fix & improve installation instructions
  pages/docs/development.mdx
Labels: documentation

#787 use node.js v16
  pages/docs/development.mdx
  pages/docs/installation/node.mdx
Labels: enhancement

#790 Upgrade Bootstrap
  __tests__/integration/html.ts
  components/Footer.tsx
  components/Image.tsx
  components/Navigation.tsx
  components/PartialMeet.tsx
  components/Subscribe.tsx
  components/docs/RuleOpsTable.tsx
  components/docs/plugins/OptionsList.tsx
  components/home/GetStarted.tsx
  components/home/IntegrationCard.tsx
  components/home/IntegrationDestinations.tsx
  components/home/IntegrationSources.tsx
  components/home/IntegrationsSection.tsx
  components/solutions/CategoryPage.tsx
  components/solutions/ComparisonPage.tsx
  components/solutions/ComparisonRow.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/integrations/bigquery-to-salesforce.tsx
  pages/integrations/postgres-to-hubspot.tsx
  pages/integrations/postgres-to-salesforce.tsx
  pages/meet.tsx
  pages/solutions/education.tsx
  pages/solutions/healthcare.tsx
  pages/trial.tsx
  pages/trial_landing.tsx
  pages/whats-new/index.tsx
  scripts/tsconfig.json
  scss/grouparoo.scss
  utils/blogTags.tsx
Labels: enhancement

#793 Show Multiple Destination Integrations
  components/BigArrow.tsx
  components/home/IntegrationMappings.tsx
  data/plugins/braze.ts
  data/plugins/customerio.ts
  data/plugins/eloqua.ts
  data/plugins/facebook.ts
  data/plugins/hubspot.ts
  data/plugins/index.ts
  data/plugins/intercom.ts
  data/plugins/iterable.ts
  data/plugins/mailchimp.ts
  data/plugins/marketo.ts
  data/plugins/mixpanel.ts
  data/plugins/onesignal.ts
  data/plugins/pardot.ts
  data/plugins/pipedrive.ts
  data/plugins/sailthru.ts
  data/plugins/salesforce.ts
  data/plugins/sendgrid.ts
  data/plugins/zendesk.ts
  pages/integrations/[type]/[plugin].tsx
  public/plugins/v1/manifest.json
Labels: enhancement

#788 App Refresh Query docs
  data/docs-nav.ts
  data/plugins/dbt.ts
  data/plugins/index.ts
  next.config.js
  pages/blog/sql-dialect-differences.mdx
  pages/blog/v06-release.mdx
  pages/docs/config/apps.mdx
  pages/docs/config/code-config/apps.mdx
  pages/docs/config/code-config/destinations.mdx
  pages/docs/config/code-config/properties.mdx
  pages/docs/config/code-config/sources.mdx
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/installation/plugins.mdx
  pages/docs/integrations.mdx
  pages/docs/integrations/grouparoo-bigquery.mdx
  pages/docs/integrations/grouparoo-braze.mdx
  pages/docs/integrations/grouparoo-calculated-property.mdx
  pages/docs/integrations/grouparoo-clickhouse.mdx
  pages/docs/integrations/grouparoo-dbt.mdx
  pages/docs/integrations/grouparoo-intercom.mdx
  pages/docs/integrations/grouparoo-marketo.mdx
  pages/docs/integrations/grouparoo-mongo.mdx
  pages/docs/integrations/grouparoo-mysql.mdx
  pages/docs/integrations/grouparoo-postgres.mdx
  pages/docs/integrations/grouparoo-redshift.mdx
  pages/docs/integrations/grouparoo-salesforce.mdx
  pages/docs/integrations/grouparoo-snowflake.mdx
  pages/docs/integrations/grouparoo-sqlite.mdx
  pages/docs/running/orchestration.mdx
  pages/public-sitemap.tsx
  pages/whats-new/2021-09-02-calculated-properties.mdx
  pages/whats-new/2021-11-15-clickhouse.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/images/docs/guides/config/app--04-configure.png
  public/images/docs/guides/config/app--05-add-refresh-query.png
  public/images/docs/guides/config/app--06-configure-refresh-query.png
  public/images/home/integrations/dbt/dbt.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
  scripts/generate_plugin_json.ts
Labels: documentation
