Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-04, with the labels that each got.

#358 Update GCP note
  pages/docs/deployment.mdx
Labels: documentation

#367 [What's New] Mongo Source
  components/docs/pluginsList.tsx
  pages/whats-new/20201-04-07-mongo-source.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/posts/releases/2021-04-07-mongo.png
  public/sitemap.xml
Labels: enhancement

#375 Store `utm_*` variables and send them with `/meet` requests
  __tests__/integration/sessionStorage.ts
  pages/_app.tsx
  pages/meet.tsx
Labels: enhancement

#365 Retrieving MongoDB fields blog post.
  data/authors.ts
  pages/blog/extracting-all-mongodb-fields.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/images/authors/paulo_ouriques.jpg
  public/posts/extracting-all-mongodb-fields/fields-usage.jpg
  public/sitemap.xml
Labels: documentation

#368 Adding CustomerIO and Pipedrive integrations pages
  data/plugins/customerio.ts
  data/plugins/index.ts
  data/plugins/pipedrive.ts
  public/images/home/integrations/customerio/customerio-person.png
  public/images/home/integrations/customerio/customerio.png
  public/images/home/integrations/customerio/grouparoo-to-customerio.png
  public/images/home/integrations/pipedrive/grouparoo-to-pipedrive.png
  public/images/home/integrations/pipedrive/pipedrive-persons.png
  public/images/home/integrations/pipedrive/pipedrive.png
  public/sitemap.xml
Labels: enhancement

#377 Google Cloud Run is not for Background jobs
  pages/blog/google-cloud-run-no-background-job.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/sitemap.xml
Labels: enhancement

#378 SEM Landing Page Tests
  pages/integrations/bigquery-to-salesforce.tsx
  pages/integrations/postgres-to-hubspot.tsx
  pages/integrations/postgres-to-salesforce.tsx
  public/sitemap.xml
Labels: enhancement

#381 Link to upgrade guides and demo `grouparoo update` command
  pages/docs/support/upgrading-grouparoo.mdx
Labels: enhancement

#382 Bring back links to upgrade guides
  pages/docs/support/upgrading-grouparoo.mdx
Labels: bug

#369 status/private needs API key
  pages/docs/support/monitoring.mdx
Labels: blocked, documentation

#383 Match https://github.com/grouparoo/app-examples/edit/main/README.md
  pages/docs/deployment.mdx
Labels: enhancement

#397 Run Dependabot Monthly
  .github/dependabot.yml
Labels: enhancement

#395 Added "about" for Teal Larson
  components/home/whoWeAre.tsx
  public/images/team/teal_larson.jpg
Labels: enhancement

#380 Upgrade guide from v0.2 to v0.3
  data/docs-nav.ts
  pages/docs/support/upgrading-grouparoo.mdx
  pages/docs/support/upgrading-grouparoo/v02-v03.mdx
  public/sitemap.xml
Labels: documentation

#400 [What's New] Declarative Sync Example App
  pages/whats-new/2021-04-20-app-example-config.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/sitemap.xml
Labels: enhancement

#404 [Blog Post] Understanding Types with SQLite and Node.js
  pages/blog/understanding-types-sqlite-node.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/understanding-types-sqlite-node/210422-sqlite-types.png
  public/sitemap.xml
Labels: enhancement

#402 Comparison pages
  __tests__/integration/comparisons.ts
  __tests__/utils/inflectors.ts
  components/footer.tsx
  pages/solutions/[id].tsx
  pages/solutions/census.mdx
  pages/solutions/hightouch.mdx
  pages/solutions/segment.mdx
  public/sitemap.xml
  utils/comparisonPages.ts
  utils/inflectors.ts
Labels: enhancement

#409 Updating UI on comparison pages
  __tests__/integration/comparisons.ts
  components/comparisons/comparisonRow.tsx
  components/comparisons/comparisonTable.tsx
  components/comparisons/featureBanner.tsx
  components/comparisons/index.tsx
  components/comparisons/sectionDivider.tsx
  components/footer.tsx
  package.json
  pages/solutions/[id].tsx
  pages/solutions/census-alternative.mdx
  pages/solutions/census.mdx
  pages/solutions/hightouch-alternative.mdx
  pages/solutions/hightouch.mdx
  pages/solutions/segment-alternative.mdx
  public/images/home/solutions/comparisons/install-code.svg
  public/images/red-x.svg
  public/sitemap.xml
  scss/grouparoo.scss
  utils/comparisonPages.ts
Labels: enhancement
