Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-12, with the labels that each got.

#795 Pricing page update
  components/solutions/ComparisonRow.tsx
  pages/pricing.module.scss
  pages/pricing.tsx
  public/images/grouparoo-blue-checkmark.svg
  public/images/grouparoo-purple-checkmark.svg
  scss/grouparoo.scss
Labels: enhancement

#815 Use `grouparoo config` in node install guide
  pages/docs/installation/node.mdx
Labels: documentation

#813 Use node 16 and remove NPM prepare step
  pages/docs/installation/docker.mdx
Labels: documentation

#816 Bootstrap theme update to fix blog tags
  next.config.js
  pages/pricing.module.scss
  pages/pricing.tsx
  scss/_variables.scss
  scss/grouparoo.scss
Labels: bug

#819 Add note about default values
  pages/docs/development/databases.mdx
Labels: documentation

#820 Update documentation on orchestration grouparoo run
  pages/docs/running/orchestration.mdx
Labels: documentation

#776 Cloud Docs
  components/docs/Image.tsx
  data/docs-nav.ts
  pages/docs/cloud.mdx
  pages/docs/cloud/repository-integration.mdx
  pages/docs/index.tsx
  public/images/docs/cloud/action-secrets.png
  public/images/docs/cloud/cloud-integrations-page-2.png
  public/images/docs/cloud/cloud-integrations-page.png
  public/images/docs/cloud/cloud-register.png
  public/images/docs/cloud/project-landing-page-click-integrations.png
  public/images/docs/cloud/project-landing-page.png
  public/images/docs/cloud/signin.png
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#824 use @use instead of @import in scss modules
  pages/pricing.module.scss
Labels: enhancement

#826 Fixing image breaking bug
  components/docs/Image.tsx
  next-env.d.ts
Labels: bug

#794 App Refresh Query/dbt blog post
  pages/blog/[post].tsx
  pages/blog/app-refresh-grouparoo-and-dbt.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/app-refresh-grouparoo-and-dbt/211130-dbt-grouparoo.png
  public/sitemap.xml
Labels: enhancement

#829 Add "Working at Grouparoo" section to About page
  components/home/WhoWeAre.tsx
  components/jobs/WorkingAtGrouparoo.tsx
  pages/about.tsx
  public/images/team/about-team.png
Labels: enhancement

#830 fix accordion
  components/docs/RuleOpsTable.tsx
  scss/grouparoo.scss
Labels: bug

#833 Update Favicons
  components/Favicon.tsx
  components/layouts/Floating.tsx
  components/layouts/Main.tsx
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-384x384.png
  public/favicon/apple-touch-icon-114x114.png
  public/favicon/apple-touch-icon-120x120.png
  public/favicon/apple-touch-icon-144x144.png
  public/favicon/apple-touch-icon-152x152.png
  public/favicon/apple-touch-icon-57x57.png
  public/favicon/apple-touch-icon-60x60.png
  public/favicon/apple-touch-icon-72x72.png
  public/favicon/apple-touch-icon-76x76.png
  public/favicon/apple-touch-icon.png
  public/favicon/browserconfig.xml
  public/favicon/code.txt
  public/favicon/favicon-128.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-196x196.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/mstile-144x144.png
  public/favicon/mstile-150x150.png
  public/favicon/mstile-310x150.png
  public/favicon/mstile-310x310.png
  public/favicon/mstile-70x70.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
  public/feeds/blog.json
  public/feeds/blog.xml
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  utils/blogPosts.ts
  utils/releaseNotes.ts
Labels: bug

#828 Remove Manual Groups
  components/docs/RuleOpsTable.tsx
  pages/docs/config/code-config/apps.mdx
  pages/docs/config/code-config/groups.mdx
  pages/docs/config/code-config/properties.mdx
  pages/docs/config/code-config/sources.mdx
  pages/docs/config/groups.mdx
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/tutorials/app-example-config.mdx
Labels: enhancement, blocked

#834 WWW Mobile/Safari fixes - AKA Safari likes being difficult
  components/home/actionable/Actionable.tsx
  components/home/features/Features.tsx
  components/home/how-it-works/HowGrouparooWorks.module.scss
  components/home/how-it-works/HowGrouparooWorks.tsx
  components/home/partners/logos/MindfulChef.tsx
  components/home/partners/logos/OneMedical.tsx
  components/home/partners/logos/Raisedev.tsx
  package-lock.json
Labels: bug

#836 Fixup Comparison Page containers and Integration Arrows on mobile
  components/home/IntegrationDestinations.tsx
  components/home/IntegrationSources.tsx
  components/solutions/ComparisonPage.tsx
  pages/integrations/[type]/[plugin].tsx
  pages/solutions/[id].tsx
Labels: bug

#837 Fix pricing page on mobile with horizontal scroll
  pages/pricing.tsx
Labels: bug

#835 navbar collapses on select on mobile
  components/Navigation.tsx
Labels: bug
