Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-02, with the labels that each got.

#180 Next v10.0.6 + rebuild package-lock.json
  components/layouts/main.tsx
  package-lock.json
  package.json
  public/feeds/blog.json
  public/feeds/blog.xml
  scss/grouparoo.scss
Labels: bug, dependencies

#188 Update main CTAs to `/docs/getting-started`
  pages/docs/deployment.mdx
  pages/docs/getting-started.mdx
  pages/index.tsx
  pages/pricing.tsx
  pages/solutions/healthcare.tsx
Labels: enhancement

#192 running grouparoo, testing grouparoo, and code-config updates
  __tests__/utils/mdxUtils.ts
  components/docs/CLICommands.tsx
  components/docs/index.tsx
  data/cli-commands.json
  data/docs-nav.ts
  pages/docs/cli.mdx
  pages/docs/cli/config.mdx
  pages/docs/cli/run.mdx
  pages/docs/cli/setup.mdx
  pages/docs/config.mdx
  pages/docs/config/code-config.mdx
  pages/docs/config/first-time-setup.mdx
  pages/docs/config/sources.mdx
  pages/docs/deployment.mdx
  pages/docs/deployment/aws-and-k8s.mdx
  pages/docs/deployment/docker.mdx
  pages/docs/development/databases.mdx
  pages/docs/development/dataflow.mdx
  pages/docs/getting-started.mdx
  pages/docs/installation.mdx
  pages/docs/installation/docker.mdx
  pages/docs/installation/node.mdx
  pages/docs/running-grouparoo.mdx
  pages/docs/running.mdx
  pages/docs/running/testing.mdx
  public/sitemap.xml
Labels: documentation

#201 Link install/docker to deploy/docker
  pages/docs/installation/docker.mdx
Labels: documentation

#193 Add migration guide for v0.1 -> v0.2
  data/docs-nav.ts
  pages/docs/support/upgrading-grouparoo.mdx
  pages/docs/support/upgrading-grouparoo/v01-v02.mdx
  public/sitemap.xml
Labels: documentation

#202 Add a diff image to the v2 upgrade guide
  pages/docs/support/upgrading-grouparoo/v01-v02.mdx
  public/images/support/upgrading-grouparoo/v0.2-upgrade-package.png
Labels: documentation

#203 Docs updates for v0.2
  pages/blog/grouparoo-monorepo-deployment.mdx
  pages/blog/product-metrics-open-source.mdx
  pages/docs/cli.mdx
  pages/docs/community/contributions.mdx
  pages/docs/config/code-config.mdx
  pages/docs/config/environment.mdx
  pages/docs/deployment/docker.mdx
  pages/docs/deployment/heroku.mdx
  pages/docs/development.mdx
  pages/docs/getting-started.mdx
  pages/docs/index.tsx
  pages/docs/installation.mdx
  pages/docs/installation/docker.mdx
  pages/docs/installation/node.mdx
  pages/docs/running/testing.mdx
  pages/docs/support/common-issues.mdx
  pages/docs/support/upgrading-grouparoo.mdx
  pages/docs/support/upgrading-grouparoo/v01-v02.mdx
  pages/index.tsx
  pages/whats-new/2020-07-29-npx.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
Labels: documentation

#204 Move to Node.js v14
  .nvmrc
  Procfile
  package.json
Labels: dependencies

#205 docs/installation/plugins
  components/docs/index.tsx
  components/docs/pluginsList.tsx
  data/docs-nav.ts
  pages/docs/cli/setup.mdx
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/installation.mdx
  pages/docs/installation/plugins.mdx
  public/sitemap.xml
Labels: enhancement

#206 plugin updates
  pages/docs/installation/plugins.mdx
Labels: enhancement

#207 Add more info about testing and demo data
  pages/docs/development.mdx
Labels: enhancement

#208 Blog Post: Gifit
  pages/blog/gifit.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/gifit/screenshot.gif
  public/posts/gifit/screenshot.png
  public/sitemap.xml
Labels: enhancement

#215 Do not use next/image for animated gifs
  components/footer.tsx
  pages/blog/gifit.mdx
Labels: bug

#217 Lock exact versions of dependencies
  package-lock.json
  package.json
Labels: dependencies

#220 Add header anchor tags to markdown rendering
  package-lock.json
  package.json
  pages/docs/development/plugins.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  utils/mdxUtils.ts
Labels: documentation, enhancement

#221 In-Page Navigation
  components/docs/CLICommands.tsx
  components/docs/tableOfContents.tsx
  components/pageNavigation.tsx
  pages/blog/[post].tsx
  pages/docs/[section]/index.tsx
  pages/docs/deployment/docker.mdx
Labels: enhancement

#222 Note about changing API_URL
  README.md
Labels: documentation

#228 Wrap all MDX headers in links
  components/docs/validateAndApplyConfig.tsx
  public/feeds/blog.json
  public/feeds/blog.xml
  scss/grouparoo.scss
  utils/mdxUtils.ts
Labels: enhancement

#229 Two new blog posts
  pages/blog/getting-previous-path-nextjs.mdx
  pages/blog/testing-session-storage-selenium-node.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/prev-page-next/current-prev-page-session.png
  public/posts/prev-page-next/next-prev-path.png
  public/posts/testing-session-storage-selenium-node/selenium-session.png
  public/sitemap.xml
Labels: enhancement

#226 Remove references to SCHEDULER
  pages/docs/deployment/aws-and-k8s.mdx
  pages/docs/deployment/docker.mdx
  pages/docs/deployment/heroku.mdx
  pages/docs/installation/docker.mdx
  pages/docs/installation/node.mdx
  pages/docs/support/environment.mdx
Labels: blocked, enhancement

#236 Remove un-used ref links and use relative links
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/installation/plugins.mdx
  pages/pricing.tsx
Labels: bug

#235 [What's New] Node.js v15 and NPM v7 Support
  pages/whats-new/2021-02-18-node15-and-npm7.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/posts/releases/2021-02-18-node15-and-npm7-node.png
  public/sitemap.xml
Labels: enhancement

#238 Homepage Messaging Revamp
  __tests__/helpers/specHelper.ts
  __tests__/integration/happyPath.ts
  __tests__/pages/careers.tsx
  __tests__/pages/index.tsx
  __tests__/pages/integrations.tsx
  components/home/getStarted.tsx
  components/icons.ts
  components/navigation.tsx
  data/plugins.ts
  pages/index.tsx
Labels: enhancement

#239 Install Instructions for AWS Linux (yum)
  pages/docs/development.mdx
  pages/docs/installation/node.mdx
Labels: enhancement

#241 Fixup support intro
  pages/docs/support.mdx
Labels: bug

#248 Nav get-started button to match index get-started button
  components/navigation.tsx
Labels: bug

#249 Improve development "Getting Started" docs
  pages/docs/development.mdx
Labels: enhancement

#251 Fix install command
  pages/docs/getting-started.mdx
  pages/index.tsx
Labels: bug

#253 New integrations pages
  data/plugins.ts
  pages/integrations/destinations/facebook.tsx
  pages/integrations/destinations/intercom.tsx
  pages/integrations/destinations/iterable.tsx
  pages/integrations/destinations/sendgrid.tsx
  public/images/home/integrations/facebook/facebook.png
  public/images/home/integrations/intercom/grouparoo-to-intercom.png
  public/images/home/integrations/intercom/intercom-list.png
  public/images/home/integrations/intercom/intercom.png
  public/images/home/integrations/iterable/grouparoo-to-iterable.png
  public/images/home/integrations/iterable/iterable-audience.png
  public/images/home/integrations/iterable/iterable.png
  public/images/home/integrations/sendgrid/grouparoo-to-sendgrid.png
  public/images/home/integrations/sendgrid/sendgrid-lists.png
  public/images/home/integrations/sendgrid/sendgrid.png
  public/sitemap.xml
Labels: enhancement

#250 Doc updates
  pages/docs/cli.mdx
  pages/docs/config/apps/community.mdx
  pages/docs/config/code-config.mdx
  pages/docs/deployment.mdx
  pages/docs/development/destinations.mdx
  pages/docs/getting-started/product-concepts.mdx
  pages/docs/running/testing.mdx
Labels: documentation

#255 [docs] run vs start and status output
  pages/docs/cli/run.mdx
Labels: documentation

#252 [docs] using .env for all environments & Testing updates
  pages/docs/running/testing.mdx
  pages/docs/support/environment.mdx
Labels: blocked, documentation

#240 [docs] Batch Generation Commands
  data/cli-commands.json
  pages/docs/cli.mdx
  pages/docs/cli/config.mdx
  pages/docs/config/apps/community.mdx
  pages/docs/config/destinations/community.mdx
  pages/docs/config/properties/community.mdx
  pages/docs/config/sources/community.mdx
  pages/docs/installation.mdx
Labels: blocked, enhancement

#259 fixup homepage layout on mobile
  components/home/getStarted.tsx
  pages/index.tsx
Labels: bug

#231 Add docs overhaul to whats-new
  pages/whats-new/2021-02-26-documentation.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/posts/releases/2021-02-18-documentation.png
  public/sitemap.xml
Labels: enhancement
