Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-06, with the labels that each got.

#506 Add MongoDB integration page.
  data/plugins/mongodb.ts
  public/images/home/integrations/mongodb/add-mongo-app.png
  public/images/home/integrations/mongodb/mongo-query-mode.png
  public/images/home/integrations/mongodb/mongo-table-mode.png
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation, enhancement

#482 Add BigQuery reference doc.
  data/docs-nav.ts
  data/plugins/googleBigQuery.ts
  pages/docs/plugins/grouparoo-bigquery.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation, enhancement

#505 Add `grouparoo/omnibus` to getting started + docker pages
  pages/docs/getting-started.mdx
  pages/docs/installation/docker.mdx
Labels: enhancement

#508 Privacy Policy
  components/footer.tsx
  data/legal/privacy.md
  pages/legal/privacy.tsx
  public/sitemap.xml
Labels: enhancement

#510 added browser frames to `/solutions` screenshots
  components/solutions/sectionDivider.tsx
  pages/solutions/census-alternative.mdx
  pages/solutions/hightouch-alternative.mdx
  pages/solutions/reverse-etl.mdx
  pages/solutions/segment-alternative.mdx
Labels: enhancement

#512 Add SQLite source integration page
  data/plugins/sqlite.ts
  public/images/home/integrations/sqlite/add-sqlite-app.png
  public/images/home/integrations/sqlite/sqlite-query-mode.png
  public/images/home/integrations/sqlite/sqlite-table-mode.png
  public/sitemap.xml
Labels: documentation, enhancement

#509 Filter and aggregationMethod examples in Property docs
  pages/docs/config/properties/community.mdx
Labels: enhancement

#481 adding examples for group rules to docs
  components/docs/ruleOpsTable.tsx
  data/property-ops-dictionary--postgres.json
  data/property-ops-dictionary--sqlite.json
  pages/docs/config/groups/community.mdx
  scss/grouparoo.scss
Labels: enhancement

#514 [Blog] Bundling and Distributing Next.js Sites via NPM
  pages/blog/distributing-nextjs-via-npm.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/distributing-nextjs-via-npm/210603-npm-nextjs.png
  public/sitemap.xml
Labels: enhancement

#515 Remove Posthog
  components/layouts/main.tsx
  components/posthog.tsx
  components/subscribe.tsx
  package-lock.json
  package.json
  pages/meet.tsx
  public/feeds/blog.json
  public/feeds/blog.xml
Labels: enhancement

#470 Added cta to main layout
  components/footer.tsx
  components/home/getStarted.tsx
  components/home/integrationsSection.tsx
  components/layouts/main.tsx
  components/solutions/categoryPage.tsx
  components/solutions/comparisonPage.tsx
  pages/docs/[section]/index.tsx
  pages/index.tsx
  pages/integrations/[type]/[plugin].tsx
  pages/integrations/bigquery-to-salesforce.tsx
  pages/integrations/postgres-to-hubspot.tsx
  pages/integrations/postgres-to-salesforce.tsx
  pages/pricing.tsx
  pages/solutions/education.tsx
  pages/solutions/healthcare.tsx
  pages/solutions/marketers.tsx
  scss/grouparoo.scss
Labels: enhancement

#518 removed "type": "date" from group rule docs
  data/property-ops-dictionary--postgres.json
  data/property-ops-dictionary--sqlite.json
Labels: documentation

#524 Revert "`head_ref` does not work in forks"
  .github/workflows/performance.yml
  .github/workflows/update-branch.yml
Labels: bug

#525 Actions cleanup
  .github/workflows/performance.yml
  .github/workflows/update-branch.yml
Labels: enhancement

#527 Swap the `npm run dev` commands so that by default we point to localhost telemetry
  package.json
Labels: enhancement

#528 Add bottom padding on job posts before CTA footer
  pages/jobs/[id].tsx
Labels: bug

#532 error on `/meet` form if no email
  pages/meet.tsx
Labels: bug

#540 Post lighthouse report to Github Issue
  .github/workflows/performance.yml
Labels: bug

#536 url and email validation
  __tests__/utils/validators.ts
  package-lock.json
  package.json
  pages/meet.tsx
  pages/trial.tsx
  utils/inflectors.ts
  utils/validators.ts
Labels: enhancement

#542 Hide gettingStarted footer from 404 and blog index pages
  components/home/getStarted.tsx
  components/layouts/main.tsx
Labels: enhancement

#543 Fix mongo pkg name
  data/plugins/mongodb.ts
  public/plugins/v1/manifest.json
Labels: bug

#544 Show link with missing href in test
  __tests__/integration/html.ts
Labels: enhancement
