Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-10, with the labels that each got.

#684 Add Braze to www with integrations page
  data/docs-nav.ts
  data/plugins/braze.ts
  data/plugins/index.ts
  pages/docs/plugins/grouparoo-braze.mdx
  public/images/home/integrations/braze/braze-user.png
  public/images/home/integrations/braze/braze.png
  public/images/home/integrations/braze/grouparoo-to-braze.png
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation

#708 Show what's new on homepage header
  components/layouts/main.tsx
Labels: enhancement

#710 Blog post: 97 things every data eng should know
  pages/blog/97-things-every-data-engineer-should-know.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/97-things-every-data-engineer-should-know/cover.jpeg
  public/sitemap.xml
Labels: hacktoberfest-accepted

#685 add models to config ui docs
  data/docs-nav.ts
  pages/docs/config/apps.mdx
  pages/docs/config/models.mdx
  pages/docs/getting-started/product-concepts.mdx
  public/images/docs/guides/config/model--01--add.png
  public/images/docs/guides/config/model--02-add.png
  public/images/docs/guides/config/model--03-name.png
  public/sitemap.xml
Labels: documentation, hacktoberfest-accepted

#751 fix image aspect ratios
  pages/docs/support/permissions.mdx
  pages/docs/support/secrets.mdx
  pages/docs/support/upgrading-grouparoo.mdx
Labels: bug

#748 Add featured blog posts to header
  __tests__/integration/blog.ts
  components/footer.tsx
  components/icons.ts
  components/navigation.tsx
  data/featuredBlogPosts.ts
Labels: enhancement
