Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-07, with the labels that each got.

#562 [SEO] meta tags/h1 updates
  components/solutions/categoryPage.tsx
  pages/solutions/customer-data-platform.mdx
  pages/solutions/modern-data-stack.mdx
  pages/solutions/reverse-etl.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  utils/solutionsPages.ts
Labels: enhancement

#563 Update to jest 27 and related packages
  __tests__/pages/careers.tsx
  __tests__/pages/index.tsx
  __tests__/pages/integrations.tsx
  jest.config.js
  jest.setup.after.ts
  jest.setup.js
  jest.setup.ts
  next-env.d.ts
  package-lock.json
  package.json
  pages/about.tsx
  pages/index.tsx
  pages/integrations/[type]/[plugin].tsx
Labels: dependencies, enhancement

#566 Update Footer CTA to "pop"
  README.md
  components/home/getStarted.tsx
  components/layouts/main.tsx
Labels: enhancement

#564 Updates for Data Engineers
  __tests__/integration/categories.ts
  components/footer.tsx
  components/navigation.tsx
  data/plugins/customerio.ts
  data/plugins/facebook.ts
  data/plugins/hubspot.ts
  data/plugins/intercom.ts
  data/plugins/iterable.ts
  data/plugins/mailchimp.ts
  data/plugins/marketo.ts
  data/plugins/onesignal.ts
  data/plugins/pipedrive.ts
  data/plugins/sailthru.ts
  data/plugins/salesforce.ts
  data/plugins/sendgrid.ts
  data/plugins/zendesk.ts
  pages/about.tsx
  pages/index.tsx
  pages/pricing.tsx
  pages/solutions/[id].tsx
  pages/solutions/census-alternative.mdx
  pages/solutions/customer-data-platform.mdx
  pages/solutions/hightouch-alternative.mdx
  pages/solutions/reverse-etl.mdx
  pages/solutions/segment-alternative.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: enhancement

#568 rebuild lockfile with newer transient deps
  package-lock.json
Labels: dependencies

#569 Remove Sean from team page
  components/home/whoWeAre.tsx
  data/authors.ts
Labels: bug

#577 Updates per semantic analysis
  pages/solutions/modern-data-stack.mdx
  pages/solutions/reverse-etl.mdx
Labels: enhancement

#582 developers use v15 of nvm
  pages/docs/development.mdx
Labels: documentation

#581 Remove footer CTA Background
  components/home/getStarted.tsx
Labels: enhancement

#583 Update node install comments
  README.md
  pages/docs/development.mdx
Labels: documentation

#587 SEO/SEM - Sitemap exclude noindex
  __tests__/integration/html.ts
  public/sitemap.xml
  utils/sitemap.ts
Labels: bug

#590 Use `next-remote-watch` for dev mode
  package-lock.json
  package.json
Labels: enhancement

#593 add page_path to ga tag
  components/googleAnalytics.tsx
  components/layouts/floating.tsx
  components/layouts/main.tsx
  pages/_app.tsx
Labels: bug
