Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-08, with the labels that each got.

#591 Add Eloqua Plugin
  data/plugins/eloqua.ts
  data/plugins/index.ts
  pages/whats-new/2021-07-28-eloqua.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/images/home/integrations/eloqua/eloqua-list.jpg
  public/images/home/integrations/eloqua/eloqua.png
  public/images/home/integrations/eloqua/grouparoo-to-eloqua.jpg
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: blocked, enhancement

#609 Add reference docs for Mongo plugin.
  components/docs/plugins/columnarSource.tsx
  components/docs/plugins/installation.tsx
  components/docs/plugins/querySource.tsx
  components/docs/plugins/tableSource.tsx
  data/docs-nav.ts
  data/plugins/index.ts
  data/plugins/mongo.ts
  data/plugins/snowflake.ts
  pages/docs/plugins/grouparoo-mongo.mdx
  pages/docs/plugins/grouparoo-snowflake.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation, enhancement

#616 Update topology image
  public/images/docs/deployment/grouparoo-deployment-topology.png
Labels: enhancement

#617 Toplogy picture update
  public/images/docs/deployment/grouparoo-deployment-topology.png
Labels: enhancement

#615 Update Team photo
  next-env.d.ts
  pages/about.tsx
  public/images/team/team-founders.jpg
  public/images/team/team.jpg
Labels: enhancement

#618 Clarify networking page
  pages/docs/support/network.mdx
  public/images/docs/deployment/grouparoo-deployment-topology-complex.png
  public/images/docs/deployment/grouparoo-deployment-topology-simple.png
Labels: enhancement

#619 Fix alternative solution typos
  pages/solutions/hightouch-alternative.mdx
Labels: bug

#620 exclude trial_landing from sitemap
  __tests__/integration/html.ts
  utils/sitemap.ts
Labels: bug

#626 add 301 redirect for cdp page
  next.config.js
Labels: enhancement

#636 Added kc to employees list
  components/home/teamMember.tsx
  components/home/whoWeAre.tsx
  public/images/team/krishna_glick.jpg
Labels: enhancement, good first issue

#637 add v0.6 migration guide
  data/docs-nav.ts
  pages/docs/support/upgrading-grouparoo.mdx
  pages/docs/support/upgrading-grouparoo/v05-v06.mdx
  public/images/docs/support/upgrading-grouparoo/v05-v06-confirm-setting.png
  public/images/docs/support/upgrading-grouparoo/v05-v06-schedule-option.png
  public/sitemap.xml
Labels: enhancement
