Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-03, with the labels that each got.

#263 Blog & What's New Pagination + What's New simplification
  __tests__/integration/html.ts
  __tests__/integration/whats-new.ts
  __tests__/utils/release-notes.ts
  components/paginationHelper.tsx
  pages/blog/author/[author]/[pageNumber].tsx
  pages/blog/author/[author]/index.tsx
  pages/blog/category/[category]/[pageNumber].tsx
  pages/blog/category/[category]/index.tsx
  pages/blog/index.tsx
  pages/blog/page/[pageNumber].tsx
  pages/whats-new/[note].tsx
  pages/whats-new/index.tsx
  pages/whats-new/page/[pageNumber].tsx
  utils/blogPosts.ts
  utils/releaseNotes.ts
Labels: enhancement

#272 [whats-new] Grouparoo CLI Updates
  pages/whats-new/2021-03-02-grouparoo-cli-updates.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/sitemap.xml
Labels: enhancement

#273 Release Notes pages always call hooks the same number of times
  pages/whats-new/[note].tsx
  pages/whats-new/index.tsx
  utils/releaseNotes.ts
Labels: bug

#277 use `main` integration branch
  README.md
  components/footer.tsx
  pages/blog/defering-side-effects-in-node.mdx
  pages/blog/grouparoo-monorepo-deployment.mdx
  pages/blog/hubspot-destination.mdx
  pages/blog/pull-the-data-you-actually-want.mdx
  pages/blog/testing-session-storage-selenium-node.mdx
  pages/docker-compose.tsx
  pages/docs/community/contributions.mdx
  pages/docs/deployment/aws-and-k8s.mdx
  pages/docs/development.mdx
  pages/docs/development/destinations.mdx
  pages/docs/development/plugins.mdx
  pages/docs/development/publishing.mdx
  pages/docs/support/legal.mdx
  pages/docs/support/telemetry.mdx
  pages/docs/support/upgrading-grouparoo.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
Labels: enhancement

#278 Notes on Example Apps
  pages/docs/development.mdx
Labels: enhancement

#281 [BLOG] Dialect differences between SQLite and Postgres in Sequelize
  __tests__/integration/blog.ts
  components/blog/authorBox.tsx
  pages/blog/author/[author]/index.tsx
  pages/blog/category/[category]/index.tsx
  pages/blog/index.tsx
  pages/blog/sql-dialect-differences.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/sql-dialect-differences/210303-databases.png
  public/sitemap.xml
Labels: enhancement

#280 Integrations refactor
  __tests__/pages/integrations.tsx
  data/plugins.ts
  data/plugins/csv.ts
  data/plugins/facebook.ts
  data/plugins/googleBigQuery.ts
  data/plugins/googleSheets.ts
  data/plugins/hubspot.ts
  data/plugins/index.ts
  data/plugins/intercom.ts
  data/plugins/iterable.ts
  data/plugins/mailchimp.ts
  data/plugins/marketo.ts
  data/plugins/mysql.ts
  data/plugins/postgres.ts
  data/plugins/redshift.ts
  data/plugins/sailthru.ts
  data/plugins/salesforce.ts
  data/plugins/sendgrid.ts
  data/plugins/snowflake.ts
  data/plugins/zendesk.ts
  pages/integrations/[type]/[plugin].tsx
  pages/integrations/destinations/facebook.tsx
  pages/integrations/destinations/hubspot.tsx
  pages/integrations/destinations/intercom.tsx
  pages/integrations/destinations/iterable.tsx
  pages/integrations/destinations/mailchimp.tsx
  pages/integrations/destinations/marketo.tsx
  pages/integrations/destinations/sailthru.tsx
  pages/integrations/destinations/salesforce.tsx
  pages/integrations/destinations/sendgrid.tsx
  pages/integrations/destinations/zendesk.tsx
  pages/integrations/sources/bigquery.tsx
  pages/integrations/sources/mysql.tsx
  pages/integrations/sources/postgres.tsx
  pages/integrations/sources/redshift.tsx
  pages/integrations/sources/snowflake.tsx
  public/sitemap.xml
Labels: enhancement

#279 Add details for common spec helper methods
  pages/docs/running/testing.mdx
Labels: blocked, documentation

#288 Un-bold integration card names
  components/home/integrationCard.tsx
Labels: bug

#289 Test with node v14
  .circleci/config.yml
  .github/workflows/update-branch.yml
Labels: enhancement

#291 Job preview Cards
  components/jobs/jobBoard.tsx
  pages/about.tsx
  pages/jobs/[id].tsx
Labels: enhancement

#295 Update links to new app-example projects
  pages/docker-compose.tsx
  pages/docs/deployment.mdx
  pages/docs/deployment/aws-and-k8s.mdx
  pages/docs/deployment/heroku.mdx
  pages/docs/installation/docker.mdx
  pages/docs/support/upgrading-grouparoo.mdx
Labels: enhancement

#297 Refrence app-examples in docs
  pages/docs/deployment.mdx
Labels: enhancement

#301 Use next/link in nav
  components/footer.tsx
  components/navigation.tsx
Labels: enhancement

#305 [whats-new] Query Source Schedules
  pages/whats-new/2021-03-12-query-source-schedules.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/posts/releases/2021-03-12-query-source-schedules.png
  public/sitemap.xml
Labels: enhancement

#312 Skip dependabot for lighthouse
  .github/workflows/performance.yml
Labels: bug

#314 Fix dependabot name
  .github/workflows/performance.yml
Labels: bug

#316 Check actor within expression
  .github/workflows/performance.yml
Labels: bug

#294 [docs] `grouparoo reset` CLI command
  data/cli-commands.json
  pages/docs/cli.mdx
  pages/docs/cli/run.mdx
  pages/docs/running.mdx
  pages/whats-new/2021-03-02-grouparoo-cli-updates.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
Labels: blocked, documentation

#317 Notes about using spec-helper in plugin tests
  pages/docs/development.mdx
Labels: enhancement

#320 Blog post: Ignoring variables when destructuring arrays
  data/authors.ts
  pages/blog/ignoring-variables-when-destructuring-arrays.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/images/authors/pedro_s_lopez.png
  public/posts/ignoring-variables-when-destructuring-arrays/surprised-destructuring.png
  public/sitemap.xml
Labels: enhancement

#324 [blog] don't use underscores in http headers
  pages/blog/dont-use-underscores-in-http-headers.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/posts/dont-use-underscores-in-http-headers/header.jpg
  public/sitemap.xml
Labels: enhancement

#325 [whats-new] Faster Installs with Precompiled UI Packages
  pages/whats-new/2021-03-18-next-precompile.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/sitemap.xml
Labels: enhancement

#327 update blog pullquote for underscores post
  pages/blog/dont-use-underscores-in-http-headers.mdx
Labels: bug

#340 Share alternative DATABASE and REDIS connection environment variables
  pages/docs/support/environment.mdx
Labels: enhancement

#350 Next.js v10.1.0
  package-lock.json
  package.json
Labels: dependencies
