Repository grouparoo/www.grouparoo.com, pull requests merged in 2021-09, with the labels that each got.

#629 Calculated Property docs
  components/docs/index.tsx
  components/docs/plugins/calculatedPropertySource.tsx
  components/docs/plugins/createApp.tsx
  components/docs/plugins/index.tsx
  data/docs-nav.ts
  pages/docs/plugins/grouparoo-calculated-property.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation

#669 pass campaign as a prop to subscribe component
  components/layouts/main.tsx
  components/subscribe.tsx
  next-env.d.ts
  pages/blog/[post].tsx
Labels: enhancement

#673 Pardot integrations docs.
  data/plugins/pardot.ts
  public/images/home/integrations/pardot/grouparoo-to-pardot.png
  public/images/home/integrations/pardot/pardot-lists.png
  public/sitemap.xml
Labels: documentation

#667 Google Sheets integration docs
  data/plugins/googleSheets.ts
  public/images/home/integrations/google-sheets/google-sheets-app.png
  public/images/home/integrations/google-sheets/google-sheets-property.png
  public/images/home/integrations/google-sheets/google-sheets-source.png
  public/sitemap.xml
Labels: documentation

#666 CSV integration docs
  data/plugins/csv.ts
  public/images/home/integrations/csv/csv-create-property.png
  public/images/home/integrations/csv/csv-remote.png
  public/sitemap.xml
Labels: documentation

#664 Marketo reference page.
  data/docs-nav.ts
  pages/docs/plugins/grouparoo-marketo.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation

#638 Salesforce reference page.
  data/docs-nav.ts
  pages/docs/plugins/grouparoo-salesforce.mdx
  public/plugins/v1/manifest.json
  public/sitemap.xml
Labels: documentation

#678 Remove S3 and File Storage
  next-env.d.ts
  pages/docs/installation/docker.mdx
  pages/docs/support/debugging.mdx
  pages/docs/support/environment.mdx
  public/images/docs/deployment/grouparoo-deployment-topology-complex.png
  public/images/docs/deployment/grouparoo-deployment-topology-simple.png
Labels: documentation

#680 Mixpanel integrations page
  data/plugins/mixpanel.ts
  public/images/home/integrations/mixpanel/grouparoo-to-mixpanel.png
  public/images/home/integrations/mixpanel/mixpanel-users.png
  public/sitemap.xml
Labels: documentation, enhancement
