Repository grouparoo/www.grouparoo.com, pull requests merged in 2022-01, with the labels that each got.

#858 Update BIMI image
  public/images/bimi-logo.svg
Labels: bug

#861 Add bottom padding to 404 page
  pages/404.tsx
Labels: bug

#862 Fix firefox `scrollToTop` bug, Disable smooth scroll
  pages/_app.tsx
  scss/_variables.scss
Labels: bug

#859 Property and Schedule Filters update
  components/docs/RuleOpsTable.tsx
  components/docs/plugins/QuerySource.tsx
  components/docs/plugins/TableSource.tsx
  data/property-ops-dictionary--postgres.json
  data/property-ops-dictionary--sqlite.json
  pages/docs/config/code-config/groups.mdx
  pages/docs/config/code-config/properties.mdx
  pages/docs/config/code-config/sources.mdx
  pages/docs/tutorials/app-example-config.mdx
Labels: documentation

#860 Add new team member
  components/home/WhoWeAre.tsx
  package-lock.json
  public/images/team/reina_feather.jpg
Labels: documentation

#867 [Blog] Typescript Types from Class Properties
  pages/blog/typescript-types-from-class-properties.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/images/authors/stephen_mash.jpeg
  public/posts/typescript-types-from-class-properties/220106-ts-types.png
  public/posts/typescript-types-from-class-properties/final-types.png
  public/posts/typescript-types-from-class-properties/hints.png
  public/sitemap.xml
Labels: enhancement

#869 Capitalization consistency on `/docs/config/destinations`
  pages/docs/config/destinations.mdx
Labels: documentation

#863 intercom destination doc
  pages/blog/97-things-every-data-engineer-should-know.mdx
  pages/docs/integrations/grouparoo-intercom.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/images/docs/integrations/intercom/intercom-app-options.png
  public/images/docs/integrations/intercom/intercom-destination-options.png
  public/images/docs/integrations/intercom/intercom-group-data.png
  public/images/docs/integrations/intercom/intercom-record-data.png
  public/images/docs/integrations/intercom/intercom-setup-1.png
  public/images/docs/integrations/intercom/intercom-setup-2.png
  scss/grouparoo.scss
Labels: documentation

#865 V0.8 upgrade guide
  data/docs-nav.ts
  pages/docs/support/upgrading-grouparoo.mdx
  pages/docs/support/upgrading-grouparoo/v07-v08.mdx
  public/images/docs/support/upgrading-grouparoo/v07-v08-model-centric-ui.png
  public/images/docs/support/upgrading-grouparoo/v07-v08-null-filter.png
  public/images/docs/support/upgrading-grouparoo/v07-v08-salesforce-export-types.png
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#871 Add Mailjet destination page, update logo, and what's new post
  data/plugins/mailjet.ts
  pages/whats-new/2021-09-01-mailjet.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/images/home/integrations/mailjet/grouparoo-to-mailjet.png
  public/images/home/integrations/mailjet/mailjet.png
  public/posts/releases/2021-09-01-mailjet.png
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#877 set default image on SEO component
  components/SEO.tsx
Labels: enhancement

#878 fix: remove extra slash from social card path
  components/SEO.tsx
Labels: bug

#875 180864002 SQLite Integration and minor edits for SendGrid
  data/docs-nav.ts
  pages/docs/integrations/grouparoo-sendgrid.mdx
  pages/docs/integrations/grouparoo-sqlite.mdx
  public/images/docs/integrations/sqlite/app/options.png
  public/images/docs/integrations/sqlite/sqlite-export-record/groups.png
  public/images/docs/integrations/sqlite/sqlite-export-record/options.png
  public/images/docs/integrations/sqlite/sqlite-export-record/records.png
  public/images/docs/integrations/sqlite/sqlite-import-table/options.png
  public/images/docs/integrations/sqlite/sqlite-import-table/property.png
  public/images/docs/integrations/sqlite/sqlite-import-table/schedule.png
Labels: documentation

#883 Reordering the APIKey recommendations
  pages/docs/support/rest-api.mdx
Labels: documentation

#873 Update docs for Model-centric UI
  pages/docs/config/apps.mdx
  pages/docs/config/destinations.mdx
  pages/docs/config/groups.mdx
  pages/docs/config/models.mdx
  pages/docs/config/properties.mdx
  pages/docs/config/records.mdx
  pages/docs/config/sources.mdx
  pages/docs/getting-started.mdx
  pages/docs/getting-started/product-concepts.mdx
  public/images/docs/guides/config/app--01-add.png
  public/images/docs/guides/config/app--02-add.png
  public/images/docs/guides/config/app--03-plugins.png
  public/images/docs/guides/config/app--04-configure.png
  public/images/docs/guides/config/app--05-add-refresh-query.png
  public/images/docs/guides/config/app--06-configure-refresh-query.png
  public/images/docs/guides/config/destination--01-add.png
  public/images/docs/guides/config/destination--02-app.png
  public/images/docs/guides/config/destination--03-name.png
  public/images/docs/guides/config/destination--04-group.png
  public/images/docs/guides/config/destination--05-property.png
  public/images/docs/guides/config/destination--06-mappings.png
  public/images/docs/guides/config/group--01-add.png
  public/images/docs/guides/config/group--02-add.png
  public/images/docs/guides/config/group--03-configure.png
  public/images/docs/guides/config/group--04-example.png
  public/images/docs/guides/config/group--05-example.png
  public/images/docs/guides/config/group--06-example.png
  public/images/docs/guides/config/model--01--add.png
  public/images/docs/guides/config/model--02-add.png
  public/images/docs/guides/config/model--02-name.png
  public/images/docs/guides/config/model--03-name.png
  public/images/docs/guides/config/model--03-overview.png
  public/images/docs/guides/config/property--01-add.png
  public/images/docs/guides/config/property--02-configure-multiple.png
  public/images/docs/guides/config/property--02-configure.png
  public/images/docs/guides/config/record--01-add.png
  public/images/docs/guides/config/record--02-add.png
  public/images/docs/guides/config/record--03-pending.png
  public/images/docs/guides/config/record--03-ready.png
  public/images/docs/guides/config/record--04-ready.png
  public/images/docs/guides/config/record--04-view-property.png
  public/images/docs/guides/config/record--04-view.png
  public/images/docs/guides/config/source--01-add.png
  public/images/docs/guides/config/source--02-choose-app.png
  public/images/docs/guides/config/source--03-configure-secondary.png
  public/images/docs/guides/config/source--03-configure.png
  public/images/docs/guides/config/source--04-mapping.png
  public/images/docs/guides/config/source--04-schedule.png
  public/images/docs/guides/config/source--05-properties.png
  public/images/docs/guides/config/source--05-schedule.png
Labels: documentation

#872 Add 0.8.0 plugins to manifest and integrations pages
  data/plugins/airtable.ts
  data/plugins/index.ts
  data/plugins/klaviyo.ts
  data/plugins/vero.ts
  public/images/docs/integrations/airtable/grouparoo-to-airtable.png
  public/images/home/integrations/airtable/airtable-records.png
  public/images/home/integrations/airtable/airtable.png
  public/images/home/integrations/airtable/grouparoo-to-airtable.png
  public/images/home/integrations/klaviyo/grouparoo-to-klaviyo.png
  public/images/home/integrations/klaviyo/klaviyo-profiles.png
  public/images/home/integrations/klaviyo/klaviyo.png
  public/images/home/integrations/vero/grouparoo-to-vero.png
  public/images/home/integrations/vero/vero-contacts.png
  public/images/home/integrations/vero/vero.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: enhancement

#879 Postgres, BigQuery, and MySQL integration docs
  components/docs/Index.tsx
  components/docs/plugins/Index.tsx
  components/docs/plugins/IntegrationNotes.tsx
  pages/docs/integrations/grouparoo-bigquery.mdx
  pages/docs/integrations/grouparoo-mysql.mdx
  pages/docs/integrations/grouparoo-postgres.mdx
  public/images/docs/integrations/bigquery/app/options.png
  public/images/docs/integrations/bigquery/import-table/mapping.png
  public/images/docs/integrations/bigquery/import-table/options.png
  public/images/docs/integrations/bigquery/import-table/property-options.png
  public/images/docs/integrations/bigquery/import-table/schedule.png
  public/images/docs/integrations/bigquery/setup/setup-1.png
  public/images/docs/integrations/mysql/app/options.png
  public/images/docs/integrations/mysql/export-record/options.png
  public/images/docs/integrations/mysql/export-record/record-data.png
  public/images/docs/integrations/mysql/import-table/options.png
  public/images/docs/integrations/mysql/import-table/properties.png
  public/images/docs/integrations/mysql/import-table/schedule.png
  public/images/docs/integrations/postgres/app/options.png
  public/images/docs/integrations/postgres/export-record/options.png
  public/images/docs/integrations/postgres/export-record/record-data.png
  public/images/docs/integrations/postgres/import-table/options.png
  public/images/docs/integrations/postgres/import-table/properties.png
  public/images/docs/integrations/postgres/import-table/schedule.png
Labels: documentation

#884 Fix visiblity of svg icons in nav dropdowns
  scss/grouparoo.scss
Labels: bug

#876 calculated property doc and images
  pages/docs/integrations/grouparoo-calculated-property.mdx
  public/images/docs/integrations/calculated-property/app/int-type.png
  public/images/docs/integrations/calculated-property/app/options.png
  public/images/docs/integrations/calculated-property/app/string-type.png
Labels: documentation

#880 Update Docker dev commands
  pages/docs/development.mdx
Labels: enhancement

#895 Update getting started video in config docs with new model-centric ui getting started video
  pages/docs/config.mdx
  pages/docs/getting-started.mdx
Labels: documentation
