Repository grouparoo/www.grouparoo.com, pull requests merged in 2022-02, with the labels that each got.

#888 18086398 Documentation Update for ClickHouse, MongoDB, Snowflake, and Redshift
  pages/docs/integrations/grouparoo-clickhouse.mdx
  pages/docs/integrations/grouparoo-mongo.mdx
  pages/docs/integrations/grouparoo-postgres.mdx
  pages/docs/integrations/grouparoo-redshift.mdx
  pages/docs/integrations/grouparoo-snowflake.mdx
  public/images/docs/integrations/clickhouse/app/options.png
  public/images/docs/integrations/clickhouse/export-record/options.png
  public/images/docs/integrations/clickhouse/export-record/properties.png
  public/images/docs/integrations/clickhouse/import-table/options.png
  public/images/docs/integrations/clickhouse/import-table/properties.png
  public/images/docs/integrations/clickhouse/import-table/schedule.png
  public/images/docs/integrations/mongo/app/options.png
  public/images/docs/integrations/mongo/import-table/filters.png
  public/images/docs/integrations/mongo/import-table/options.png
  public/images/docs/integrations/mongo/import-table/properties.png
  public/images/docs/integrations/mongo/import-table/schedule.png
  public/images/docs/integrations/redshift/app/options.png
  public/images/docs/integrations/redshift/export-record/options.png
  public/images/docs/integrations/redshift/export-record/properties.png
  public/images/docs/integrations/redshift/import-table/options.png
  public/images/docs/integrations/redshift/import-table/properties.png
  public/images/docs/integrations/snowflake/app/options.png
  public/images/docs/integrations/snowflake/import-table/mapping.png
  public/images/docs/integrations/snowflake/import-table/options.png
  public/images/docs/integrations/snowflake/import-table/property.png
  public/images/docs/integrations/snowflake/import-table/schedule.png
  public/images/docs/integrations/snowflake/setup/setup-1.png
Labels: documentation

#915 Remove generator from Product Concepts table of contents
  pages/docs/getting-started/product-concepts.mdx
Labels: bug, documentation

#887 Added 08 Whats New Page + Image
  pages/whats-new/2022-01-28-v08.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/posts/v08-release/model-overview-ui.png
Labels: documentation

#916 Remove app-example-config tutorial from docs and tutorials section
  components/docs/plugins/TableSource.tsx
  data/docs-nav.ts
  pages/docs/tutorials.mdx
  pages/docs/tutorials/app-example-config.mdx
  pages/whats-new/2021-04-20-app-example-config.mdx
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#921 Adding links to our terms and privacy pages
  components/TrialForm.tsx
  pages/meet.tsx
  pages/trial_landing.tsx
Labels: enhancement

#918 Add Configuration Files support docs
  data/docs-nav.ts
  pages/docs/support/config-files.mdx
  pages/docs/support/config-files/advanced-usage.mdx
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#922 Prevent Vercel from adding deployment comments to PRs and the main branch
  vercel.json
Labels: enhancement

#919 Redesign: Get Started and Pricing pages
  components/getStarted/GetStartedCard.tsx
  components/layouts/Main.tsx
  components/pricing/PricingCard.module.scss
  components/pricing/PricingCard.tsx
  components/pricing/PricingPlan.module.scss
  components/pricing/PricingPlans.tsx
  components/pricing/PricingTable.tsx
  components/solutions/ComparisonTable.tsx
  pages/get-started.tsx
  pages/pricing.module.scss
  pages/pricing.tsx
  public/images/home/get-started/cloud-cycle.svg
  public/images/home/get-started/server.svg
  scss/grouparoo.scss
Labels: enhancement

#924 Remove code config docs, add redirects, and update code-config links to new paths
  components/docs/GeneratedConfigFile.tsx
  components/docs/plugins/CreateApp.tsx
  components/docs/plugins/TableSource.tsx
  data/docs-nav.ts
  next.config.js
  pages/blog/a-single-source-of-truth.mdx
  pages/blog/sql-dialect-differences.mdx
  pages/docs/config/apps.mdx
  pages/docs/config/code-config.mdx
  pages/docs/config/code-config/apps.mdx
  pages/docs/config/code-config/destinations.mdx
  pages/docs/config/code-config/groups.mdx
  pages/docs/config/code-config/properties.mdx
  pages/docs/config/code-config/sources.mdx
  pages/docs/config/destinations.mdx
  pages/docs/config/groups.mdx
  pages/docs/config/properties.mdx
  pages/docs/config/sources.mdx
  pages/docs/integrations/grouparoo-bigquery.mdx
  pages/docs/integrations/grouparoo-clickhouse.mdx
  pages/docs/integrations/grouparoo-google-sheets.mdx
  pages/docs/integrations/grouparoo-mongo.mdx
  pages/docs/integrations/grouparoo-mysql.mdx
  pages/docs/integrations/grouparoo-postgres.mdx
  pages/docs/integrations/grouparoo-salesforce.mdx
  pages/docs/integrations/grouparoo-snowflake.mdx
  pages/docs/integrations/grouparoo-sqlite.mdx
  pages/docs/support/config-files.mdx
  pages/docs/support/upgrading-grouparoo/v04-v05.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#925 Remove unused components now that we don't have `grouparoo generate`
  components/docs/Index.tsx
  components/docs/plugins/CalculatedPropertySource.tsx
  components/docs/plugins/ColumnarDestination.tsx
  components/docs/plugins/ColumnarSource.tsx
  components/docs/plugins/CreateApp.tsx
  components/docs/plugins/Index.tsx
  components/docs/plugins/QuerySource.tsx
  components/docs/plugins/TableSource.tsx
Labels: documentation

#929 fix: don't overflow nav on tablets
  components/Navigation.tsx
Labels: bug

#928 airtable doc, images, and navigation
  data/docs-nav.ts
  pages/docs/integrations/grouparoo-airtable.mdx
  public/images/docs/integrations/airtable/app/options.png
  public/images/docs/integrations/airtable/export-records/options.png
  public/images/docs/integrations/airtable/export-records/properties.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#931 bring back header integration footnote
  __tests__/pages/index.tsx
  components/home/header/Header.tsx
  pages/index.tsx
Labels: enhancement

#932 180915373 filters aggregations notes
  pages/docs/getting-started/product-concepts.mdx
Labels: documentation

#930 zendesk doc, images, and navigation
  data/docs-nav.ts
  pages/docs/integrations/grouparoo-zendesk.mdx
  public/images/docs/integrations/zendesk/app/options.png
  public/images/docs/integrations/zendesk/export-users/groups.png
  public/images/docs/integrations/zendesk/export-users/properties.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#935 onesignal docs, images, and navigation added
  data/docs-nav.ts
  pages/docs/integrations/grouparoo-onesignal.mdx
  public/images/docs/integrations/onesignal/app/options.png
  public/images/docs/integrations/onesignal/export-users/groups.png
  public/images/docs/integrations/onesignal/export-users/properties.png
  public/images/docs/integrations/onesignal/setup/setup-1.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#939 Remove references to Mongo Query Import
  data/plugins/clickhouse.ts
  data/plugins/csv.ts
  data/plugins/eloqua.ts
  data/plugins/googleBigQuery.ts
  data/plugins/googleSheets.ts
  data/plugins/index.ts
  data/plugins/intercom.ts
  data/plugins/mongo.ts
  data/plugins/mysql.ts
  data/plugins/postgres.ts
  data/plugins/redshift.ts
  data/plugins/snowflake.ts
  data/plugins/sqlite.ts
  pages/docs/integrations/grouparoo-mongo.mdx
Labels: documentation

#940 Update HubSpot to use capital S
  components/Footer.tsx
  components/documents/data-sync-data.mdx
  data/docs-nav.ts
  data/plugins/hubspot.ts
  pages/blog/building-a-sync-engine.mdx
  pages/blog/customer-data-integration.mdx
  pages/blog/operational-analytics.mdx
  pages/blog/seed-round.mdx
  pages/blog/types-of-apis.mdx
  pages/blog/using-sync-modes.mdx
  pages/blog/what-is-a-data-pipeline.mdx
  pages/blog/what-is-data-synchronization.mdx
  pages/blog/what-is-the-etl-process.mdx
  pages/docs/deployment/secrets.mdx
  pages/docs/support/config-files.mdx
  pages/meet.tsx
  pages/solutions/hightouch-alternative.mdx
  pages/solutions/reverse-etl.mdx
  pages/whats-new/2020-06-26-hubspot.mdx
  public/feeds/blog.json
  public/feeds/blog.xml
  public/feeds/whatsnew.json
  public/feeds/whatsnew.xml
  public/plugins/v1/manifest.json
Labels: documentation

#936 use TrialForm component on trial_landing page
  pages/trial_landing.tsx
Labels: enhancement

#933 180770335 airtable doc
  pages/docs/integrations/grouparoo-airtable.mdx
  public/images/docs/integrations/airtable/setup/setup-1.png
Labels: documentation

#941 iterable doc, images, and navigation
  data/docs-nav.ts
  pages/docs/integrations/grouparoo-iterable.mdx
  public/images/docs/integrations/iterable/app/options.png
  public/images/docs/integrations/iterable/export-users/groups.png
  public/images/docs/integrations/iterable/export-users/new-field.png
  public/images/docs/integrations/iterable/export-users/properties.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#942 customer.io docs, images and navigation
  data/docs-nav.ts
  pages/docs/integrations/grouparoo-customerio.mdx
  public/images/docs/integrations/customerio/app/options.png
  public/images/docs/integrations/customerio/export-customers/groups.png
  public/images/docs/integrations/customerio/export-customers/optional.png
  public/images/docs/integrations/customerio/export-customers/properties.png
  public/plugins/v1/manifest.json
  public/public-sitemap.json
  public/sitemap.xml
Labels: documentation

#943 Utilize newer styled components where able
  components/Code.tsx
  components/CodeBlock.tsx
  components/Footer.tsx
  components/Subscribe.tsx
  components/docs/RuleOpsTable.tsx
  components/home/HomepageCodeBox.tsx
  components/home/IntegrationButton.tsx
  components/home/IntegrationCard.tsx
  components/home/IntegrationDestinations.tsx
  components/home/IntegrationInstallation.tsx
  components/home/IntegrationSources.tsx
  components/home/IntegrationsSection.tsx
  components/home/about/About.tsx
  components/home/integrations/Integrations.tsx
  components/layouts/Main.tsx
  components/subscribe/Subscribe.module.scss
  components/subscribe/Subscribe.tsx
  pages/blog/[post].tsx
  pages/integrations.tsx
  pages/integrations/[type]/[plugin].tsx
  pages/solutions/education.tsx
  pages/solutions/healthcare.tsx
Labels: enhancement
